sudo: false

language: php

notifications:
  email: false

branches:
  only:
    - master

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest PHP_LINT=1

    - php: 5.6
      env: WP_VERSION=latest PHP_LINT=1

    - php: 7.0
      env: WP_VERSION=trunk PHP_LINT=1 QUNIT=1
    - php: 7.0
      env: WP_VERSION=latest QUNIT=1

    - php: 7.1
      env: WP_VERSION=latest PHP_LINT=1

before_script:
  - |
    if [[ "$QUNIT" == "1" ]]; then
      npm install
    fi

script:
  - |
    if [[ "$PHP_LINT" == "1" ]]; then
      find . -type "f" -iname "*.php" | xargs -L "1" php -l
    fi

  - |
    if [[ "$QUNIT" == "1" ]]; then
      grunt qunit:specific --wp=$WP_VERSION
    fi
