sudo: false

language: php

notifications:
  email: false

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest PHP_LINT=1

    - php: 5.6
      env: WP_VERSION=latest PHP_LINT=1

    # If we end up using WP_VERSION=x.y.z we could call `qunit:specific --wp=$WP_VERSION`.
    - php: 7.0
      env: WP_VERSION=trunk PHP_LINT=1
    - php: 7.0
      env: WP_VERSION=latest QUNIT_RECENT=1

    - php: 7.1
      env: WP_VERSION=latest PHP_LINT=1

before_script:
  - |
    if [[ "$QUNIT_RECENT" == "1" ]]; then
      npm install
    fi

script:
  - |
    if [[ "$PHP_LINT" == "1" ]]; then
      find . -type "f" -iname "*.php" | xargs -L "1" php -l
    fi

  - |
    if [[ "$QUNIT_RECENT" == "1" ]]; then
      grunt qunit:recent
    fi
